# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

vmult <- function(m1, m2) {
    .Call('_HOME_vmult', PACKAGE = 'HOME', m1, m2)
}

vvmult <- function(m1, m2) {
    .Call('_HOME_vvmult', PACKAGE = 'HOME', m1, m2)
}

vvvmult <- function(m1, m2) {
    .Call('_HOME_vvvmult', PACKAGE = 'HOME', m1, m2)
}

llpruning <- function(nodes, edges, el, L, eig_val, eig_vect, ivp, propinv) {
    .Call('_HOME_llpruning', PACKAGE = 'HOME', nodes, edges, el, L, eig_val, eig_vect, ivp, propinv)
}

